In [1]:
import numpy as np
import pandas as pd

In [6]:
data=pd.read_csv(r"C:\ineuron\fsdm_endtoend\notebooks\data\gemstone.csv")

In [8]:
data.drop(labels=["id"],axis=1)

        carat        cut color clarity  depth  table     x     y     z  price
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453
...       ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67   1130
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47   2874
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62   3036
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81    681
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48   2258

[193573 rows x 10 columns]

In [9]:
x=data.drop(labels=["price"],axis=1)

In [14]:
x

            id  carat        cut color clarity  depth  table     x     y     z
0            0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1            1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2            2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3            3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4            4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...        ...    ...        ...   ...     ...    ...    ...   ...   ...   ...
193568  193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569  193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570  193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571  193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572  193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 10 columns]

In [12]:
y=data[["price"]]

In [13]:
y

        price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [15]:
categorical_cols=x.select_dtypes(include='object').columns
numerical_cols=x.select_dtypes(exclude='object').columns

In [16]:
numerical_cols

Index(['id', 'carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [17]:
x.select_dtypes(include='object')

              cut color clarity
0         Premium     F     VS2
1       Very Good     J     SI2
2           Ideal     G     VS1
3           Ideal     G     VS1
4         Premium     G     VS2
...           ...   ...     ...
193568      Ideal     D    VVS2
193569    Premium     G    VVS2
193570  Very Good     F     SI1
193571  Very Good     D     SI1
193572       Good     E     SI2

[193573 rows x 3 columns]

In [18]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good','Premium','Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']

In [19]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [21]:
num_pipeline=Pipeline(
    
    
    steps=[
        
        ('imputer',SimpleImputer()),
        ('scaler', StandardScaler())
    ]
    
    
)

In [20]:
cat_pipeline=Pipeline(
    
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('ordinalencoder',OrdinalEncoder(categories=[cut_categories,color_categories,clarity_categories]))
    ]
    
)

In [22]:
preprocessor=ColumnTransformer(
    [
        
        ('num_pipeline',num_pipeline,numerical_cols),
        ('cat_pipeline',cat_pipeline,categorical_cols)
    ]
)

In [23]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=30)

In [24]:
preprocessor.fit_transform(X_train)

array([[ 1.27491908, -0.97543926, -0.84960654, ...,  4.        ,
         5.        ,  5.        ],
       [-1.10290693,  0.2351953 ,  1.83363716, ...,  1.        ,
         1.        ,  2.        ],
       [-0.99761317,  0.49461699,  0.81585507, ...,  3.        ,
         3.        ,  4.        ],
       ...,
       [ 0.03428   ,  0.45138004,  1.55606023, ...,  1.        ,
         3.        ,  2.        ],
       [-0.87327749,  0.66756478, -1.77486298, ...,  4.        ,
         3.        ,  4.        ],
       [ 1.3030439 ,  0.25681377,  0.81585507, ...,  4.        ,
         3.        ,  2.        ]])

In [25]:
preprocessor.transform(X_test)

array([[-0.47300385, -0.56468825, -0.94213218, ...,  3.        ,
         1.        ,  3.        ],
       [-0.57300521, -0.17555571,  1.00090636, ...,  2.        ,
         4.        ,  2.        ],
       [ 1.58109167, -1.06191316,  0.2607012 , ...,  4.        ,
         4.        ,  7.        ],
       ...,
       [-0.93195878, -0.19717419, -3.34779894, ...,  3.        ,
         6.        ,  3.        ],
       [-1.198492  , -0.82410994, -0.20192702, ...,  4.        ,
         3.        ,  2.        ],
       [-0.61614902,  2.61322747, -0.75708089, ...,  3.        ,
         6.        ,  3.        ]])

In [26]:
preprocessor.get_feature_names_out()

array(['num_pipeline__id', 'num_pipeline__carat', 'num_pipeline__depth',
       'num_pipeline__table', 'num_pipeline__x', 'num_pipeline__y',
       'num_pipeline__z', 'cat_pipeline__cut', 'cat_pipeline__color',
       'cat_pipeline__clarity'], dtype=object)

In [27]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [28]:
X_train

,num_pipeline__id,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,1.274919,-0.975439,-0.849607,-0.121531,-1.042757,-1.080970,-1.123150,4.0,5.0,5.0
1,-1.102907,0.235195,1.833637,-0.121531,0.318447,0.279859,0.485354,1.0,1.0,2.0
2,-0.997613,0.494617,0.815855,0.399800,0.570855,0.606458,0.673737,3.0,3.0,4.0
3,-1.173764,-1.018676,0.260701,0.921131,-1.214034,-1.244270,-1.195605,3.0,3.0,3.0
4,-0.914812,-0.953821,-0.664555,-0.642862,-1.069801,-1.044681,-1.094168,4.0,6.0,5.0
...,...,...,...,...,...,...,...,...,...,...
135496,-0.544112,-1.040295,-0.016876,-0.642862,-1.268122,-1.244270,-1.239078,4.0,1.0,2.0
135497,-0.905908,0.991842,0.168176,-0.642862,1.048629,1.114501,1.079486,4.0,3.0,1.0
135498,0.034280,0.451380,1.556060,-0.642862,0.516768,0.588314,0.702719,1.0,3.0,2.0
135499,-0.873277,0.667565,-1.774863,1.442462,0.868337,0.951202,0.688228,4.0,3.0,4.0
135500,1.303044,0.256814,0.815855,-0.121531,0.381549,0.415942,0.470863,4.0,3.0,2.0

In [29]:
X_test

,num_pipeline__id,num_pipeline__carat,num_pipeline__depth,num_pipeline__table,num_pipeline__x,num_pipeline__y,num_pipeline__z,cat_pipeline__cut,cat_pipeline__color,cat_pipeline__clarity
0,-0.473004,-0.564688,-0.942132,-0.642862,-0.429765,-0.464061,-0.500036,3.0,1.0,3.0
1,-0.573005,-0.175556,1.000906,-0.121531,-0.042137,-0.028595,0.036132,2.0,4.0,2.0
2,1.581092,-1.061913,0.260701,-0.121531,-1.304180,-1.298703,-1.268060,4.0,4.0,7.0
3,-0.218647,0.970223,-0.201927,1.963794,1.048629,0.996563,0.978049,3.0,3.0,3.0
4,-1.160998,-0.932202,-1.312235,0.399800,-1.006699,-0.990248,-1.065186,3.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...
58067,1.713008,1.013460,1.185958,-0.642862,1.003556,1.041924,1.151941,2.0,4.0,3.0
58068,0.662413,-0.997058,0.260701,-1.164193,-1.141917,-1.126331,-1.108659,4.0,2.0,6.0
58069,-0.931959,-0.197174,-3.347799,1.442462,0.102096,0.071199,-0.224706,3.0,6.0,3.0
58070,-1.198492,-0.824110,-0.201927,-0.121531,-0.853450,-0.881382,-0.876803,4.0,3.0,2.0
58071,-0.616149,2.613227,-0.757081,1.442462,2.139394,2.039865,2.006912,3.0,6.0,3.0

In [30]:
"""linear regression
ridge regression
lasso regression
elastic net"""

'linear regression\nridge regression\nlasso regression\nelastic net'

In [31]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [40]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [32]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

In [33]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [34]:
list(models)

['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet']

In [35]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(model)

LinearRegression()
Lasso()
Ridge()
ElasticNet()

In [37]:
models.keys()

dict_keys(['LinearRegression', 'Lasso', 'Ridge', 'Elasticnet'])

In [38]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet()])

In [41]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    #this is a validation(test) score
    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 1013.904802565844
MAE: 674.0257224619522
R2 score 93.68908132630604
===================================


Lasso
Model Training Performance
RMSE: 1013.8723151331255
MAE: 675.2036875769028
R2 score 93.68948574743231
===================================


Ridge
Model Training Performance
RMSE: 1013.9059934108639
MAE: 674.0567268148469
R2 score 93.6890665017772
===================================


Elasticnet
Model Training Performance
RMSE: 1513.9182183448397
MAE: 1050.754957945767
R2 score 85.92970983426311
===================================